FROM localhost/base

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=80

# Build the app.

WORKDIR /app
COPY . .

RUN npm install --legacy-peer-deps; \
    npm run build;

# Run the app.

CMD npm run start -- -H "$HOST" -p "$PORT";

EXPOSE 80
