FROM node:current-alpine

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=80

# https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile#L5
RUN apk add --no-cache libc6-compat;

# Build the app.

WORKDIR /app
COPY . .

RUN npm install; \
    npm run build;

# Run the app.

CMD npm run start -- -H "$HOST" -p "$PORT";

EXPOSE 80
