#!/bin/bash

_CURRENT_DIR=$(dirname "$0")
source $_CURRENT_DIR/_vars.sh

IMAGE_REGISTRY=${IMAGE_REGISTRY:-""}
REGISTRY_USER=${REGISTRY_USER:-""}
REGISTRY_PASSWORD=${REGISTRY_PASSWORD:-""}

$PODMAN login --username $REGISTRY_USER --password $REGISTRY_PASSWORD $IMAGE_REGISTRY
$PODMAN push $IMAGE $IMAGE_REGISTRY/$IMAGE
